#!/bin/sh
#
# fluxbox startup-script:
#  By KinG-InFeT

# Per la keymap:
xmodmap "/root/.Xmodmap"

#impostare sfondo default
feh --bg-scale /root/img/sfondo.jpg

#impostare programmi in avvio permanenti
conky &
/opt/lampp/lampp start &
/usr/lib/notification-daemon-1.0/notification-daemon &

#deluge &

#sh /root/jd.sh &

#sleep 10

#wbar -bpress -above-desk -pos top -isize 46.0 -balfa 100.0 -falfa 78.0 -zoomf 1.6 -jumpf 1.0 &
#wbar -bpress -above-desk -pos top &

#da non levare
exec /usr/bin/fluxbox -log ~/.fluxbox/log


